version: '3.7'

services:
  airflow-webserver:
    image: apache/airflow:2.8.1
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__WEBSERVER__DEFAULT_USER_USERNAME: airflow
      AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD: airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.utils.email.send_email_smtp
      AIRFLOW__SMTP__SMTP_HOST: ${EMAIL_HOST}
      AIRFLOW__SMTP__SMTP_STARTTLS: 'True'
      AIRFLOW__SMTP__SMTP_SSL: 'False'
      AIRFLOW__SMTP__SMTP_USER: ${EMAIL_USER}
      AIRFLOW__SMTP__SMTP_PORT: ${EMAIL_PORT}
      AIRFLOW__SMTP__SMTP_PASSWORD: ${EMAIL_PASSWORD}
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ${EMAIL_FROM}

    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    restart: always
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.8.1
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.utils.email.send_email_smtp
      AIRFLOW__SMTP__SMTP_HOST: ${EMAIL_HOST}
      AIRFLOW__SMTP__SMTP_STARTTLS: 'True'
      AIRFLOW__SMTP__SMTP_SSL: 'False'
      AIRFLOW__SMTP__SMTP_USER: ${EMAIL_USER}
      AIRFLOW__SMTP__SMTP_PORT: ${EMAIL_PORT}
      AIRFLOW__SMTP__SMTP_PASSWORD: ${EMAIL_PASSWORD}
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ${EMAIL_FROM}

    volumes:
      - ./dags:/opt/airflow/dags
    restart: always
    command: scheduler

  airflow-init:
    image: apache/airflow:2.8.1
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}

    volumes:
      - ./dags:/opt/airflow/dags
    entrypoint: ["bash", "-c", "airflow db init"]
